# Generated by Django 5.2 on 2025-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='review',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
