# Generated by Django 5.2 on 2025-05-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fecha_review',
            field=models.DateField(auto_now_add=True),
        ),
    ]
